### ISSUE TITLE
웹 클라이언트 배포 수단 선택

### ISSUE THREAD

**Issue by hyesungoh** [dogVelopers/whereWeGoWebClient#25]
배포 수단으로 현재 2가지 방법을 고민하고 있습니다

## 1. [`Vercel`](https://vercel.com/docs) hobby plan 사용

장점
- 무료
- 쉬움

단점
- 매달 20 달러가 부과되는 pro plan을 사용하지 않을 시 수익창출 불가

## 2. AWS (EC2 혹은 lambda) 사용

장점 
- google ads 부착 가능 (수익 창출 가능)
- 안해본 방법이라 공부할 수 있음

단점
- 요금이 생각보다 더 부과될 수도 있음
- 안해본 방법이라 시간이 더욱 걸릴 수 있음

## 부탁드리는 점

둘 중 어느 방법이 적절한 지 의견을 공유해주셨으면 합니다 👍

**Comment by suyeonii99** [comment]
두 방법 다 각 장점이 있지만 아무래도 AWS를 사용해 배포하는게 추후 더 도움이 될 것 같습니다 !
하지만 혹시 마감기한까지 새로이 공부하기에 시간이 촉박하다면 Vercel hobby plan 을 사용하는 것이 좋지 않을까 합니당

**Comment by doeunllee** [comment]
저도 수연님 의견과 같습니다 😃

**Comment by jieunee2** [comment]
둘 다 좋은 방법이라고 생각하지만 수익 창출이 가능하고 한 번 사용해보았던 AWS를 이용하는 것이 낫다고 생각합니다 ! 🙂
